- Cargo.lock
- Cargo.toml
- README.md
* `freesound-credits`: 0.2.2 -> 0.2.3
</p></details>
---
> chore: release v0.2.3

- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.4 -> 0.2.5
</p></details>
---
> chore: release v0.2.5

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.9 -> 0.2.10
<blockquote>
- removed cliff altogether
- trying to switch to keep a changelog
- empty the changelog
- Empty the changelog
- Trying to switch to keep a changelog
- Trying to switch to keep a changelog (#12)
- Removed cliff altogether
</blockquote>
</p></details>
---
> chore: release v0.2.10

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.10 -> 0.2.11
<blockquote>
- single git tag and tag template
- binstall name var
- remove configs with default values
</blockquote>
</p></details>
---
> chore: release v0.2.11

- .pre-commit-config.yaml
markdownlint-fix solves an issue and creates another: its fixes are unsigned. all commits have to be signed off.
> fix(pre-commit): don't fix. it is unsigned

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.11 -> 0.2.12
<blockquote>
- Adding pre-commit hook for convetional - ([924c906](https://github.com/gacallea/freesound-credits/commit/924c906c4b662503d8e25199c44780608c323557)) by 
- *(changelog)* Better template, less redundant, fix broken links - ([d2512ae](https://github.com/gacallea/freesound-credits/commit/d2512aeb81a63d7282f15f60fbc9bcc1f6daec60)) by 
- *(changelog)* New template Closes [#22](https://github.com/gacallea/freesound-credits/pull/22) - ([2e421a9](https://github.com/gacallea/freesound-credits/commit/2e421a9db04693c5a388d05c411cac0565da7047)) by 
- *(pre-commit)* Don't fix. it is unsigned - ([8b544cf](https://github.com/gacallea/freesound-credits/commit/8b544cf883c7f9b3e3bde1e61be6a086682545db …
> chore: release v0.2.12

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.13 -> 0.2.14
<blockquote>
- *(readme)* Added commitlint badge + reoder ([#29](https://github.com/gacallea/freesound-credits/pull/29)) - ([7da5d62](https://github.com/gacallea/freesound-credits/commit/7da5d62f3db17c1229cd183fc7f72d3e5f3139e5))
- *(release-plz)* Use release.link ([#35](https://github.com/gacallea/freesound-credits/pull/35)) - ([491f627](https://github.com/gacallea/freesound-credits/commit/491f62731568cb17814b4bbdbdb9eab50c4a1fc1))
- *(readme)* Renamed commitlint to .yml ([#31](https://github.com/gacallea/freesound-credits/pull/31)) - ([d5550ef](https://github.com/gacallea/freesound-credits/commit/d5550efe38d2d943382ca9dafe2ad9fe9ce48f3b))
- *(release-plz)* Remote.link in links was broken …
> chore: release v0.2.14

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.14 -> 0.2.15
<blockquote>
- *(spellcheck)* Add spellcheck precommit ci and config ([#39](https://github.com/gacallea/freesound-credits/pull/39)) - ([727e79e](https://github.com/gacallea/freesound-credits/commit/727e79edea0a0fe902fa9a5dfb63a90f5a621992))
- *(spellcheck)* +top number -precomit ([#40](https://github.com/gacallea/freesound-credits/pull/40)) - ([139ffc9](https://github.com/gacallea/freesound-credits/commit/139ffc90b774bb292f7030f0e07e3e472543a8d6))
- Streamline pipelines ([#42](https://github.com/gacallea/freesound-credits/pull/42)) - ([f8f33e8](https://github.com/gacallea/freesound-credits/commit/f8f33e89092727cc19a844bc81f6d1a31e911570))
- Rm redundant freesound in frontmatter …
> chore: release v0.2.15

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.16 -> 0.2.17 (✓ API compatible changes)
<blockquote>
- Minor fixes ([#58](https://github.com/gacallea/freesound-credits/pull/58)) - ([533c81a](https://github.com/gacallea/freesound-credits/commit/533c81ac7944c145c0bb060d2a9f9f9b5d7ed662))
</blockquote>
</p></details>
---
> chore: release v0.2.17

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.20 -> 0.2.21 (✓ API compatible changes)
<blockquote>
- Update Cargo.lock dependencies - ([0000000](https://github.com/andreacfromtheapp/freesound-credits/commit/0000000))
</blockquote>
</p></details>
---
> chore: release v0.2.21

- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.22 -> 0.2.23 (✓ API compatible changes)
<blockquote>
- Update Cargo.lock dependencies - ([0000000](https://github.com/andreacfromtheapp/freesound-credits/commit/0000000))
</blockquote>
</p></details>
---
> chore: release v0.2.23

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.23 -> 0.2.24 (✓ API compatible changes)
<blockquote>
- Minor updates (#87) - ([6449396](https://github.com/andreacfromtheapp/freesound-credits/commit/64493962e7c89c482303eaa96e14df07f09ff425))
</blockquote>
</p></details>
---
> chore: release v0.2.24

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.24 -> 0.2.25 (✓ API compatible changes)
<blockquote>
- Add workflows and pre-hooks and vale (#90) - ([c806e54](https://github.com/andreacfromtheapp/freesound-credits/commit/c806e54dc42fe4beed4bcc33342463a574c693fc))
</blockquote>
</p></details>
---
> chore: release v0.2.25

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.25 -> 0.2.26 (✓ API compatible changes)
<blockquote>
- Fix docs (#98) - ([3d2bf2f](https://github.com/andreacfromtheapp/freesound-credits/commit/3d2bf2f338150082a301cc0cd2d3bff6ab1f959f))
</blockquote>
</p></details>
---
> chore: release v0.2.26

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.26 -> 0.2.27 (✓ API compatible changes)
</p></details>
---
> chore: release v0.2.27

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.27 -> 0.2.28 (✓ API compatible changes)
</p></details>
---
> chore: release v0.2.28

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.28 -> 0.2.29 (✓ API compatible changes)
</p></details>
---
> chore: release v0.2.29

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.29 -> 0.2.30 (✓ API compatible changes)
</p></details>
---
> chore: release v0.2.30

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.30 -> 0.2.31 (✓ API compatible changes)
</p></details>
---
> chore: release v0.2.31

- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.32 -> 0.2.33 (✓ API compatible changes)
</p></details>
---
> chore: release v0.2.33

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.33 -> 0.2.34 (✓ API compatible changes)
</p></details>
---
> chore: release v0.2.34
