andreacfromtheapp/freesound-credits

- .github/dependabot.yml
- .github/workflows/cargo-assist.yml
- Cargo.lock
- Cargo.toml
- README.md
- cliff.toml
> chore: path bump for ci improvements

- .gitignore
is empty enough? I hope so FFS!
> ci: adding emtpy chagelog file cause cargo-dist needs it.

- .github/workflows/release.yml
- Cargo.toml
cargo-dist 0.19.1 -> 0.20.0
cargo.toml config bump
release.yml to use new version in action
> chore: update cargo-dist

- .pre-commit-config.yaml
making sure commits adhere to conventional commits with https://github.com/compilerla/conventional-pre-commit
> feat: adding pre-commit hook for convetional

- CHANGELOG.md
- release-plz.toml
added templating to release-plz.toml
migrated CHANGELOG.md to the new templte with gitc-liff
changelog should be ready for plz action
> fix(changelog): new template Closes #22

- CHANGELOG.md
- release-plz.toml
filter out merge commits, release messages, fix links to pr/issues better temlate all round finally!
> fix(changelog): better template, less redundant, fix broken links

- CHANGELOG.md
- release-plz.toml
> fix(release-plz): improvements all around

- .github/workflows/commitlint.yaml
- .pre-commit-config.yaml
> ci(action): add commitlint on push main and PRs

- README.md
> feat(readme): added commitlint badge + reoder

- release-plz.toml
> fix(release-plz): remote.link in links was broken

- README.md
> docs(readme): better wording. fix typos

- CHANGELOG.md
- release-plz.toml
> feat(release-plz): use release.link

- .github/workflows/cargo-assist.yml
- .github/workflows/ci.yml
- .github/workflows/commitlint.yml
- .github/workflows/markdownlint-cli2.yml
- .github/workflows/release-plz.yml
- .github/workflows/trufflehog.yml
- .markdownlint-cli2.yaml
- .markdownlintignore
- .pre-commit-config.yaml
- README.md
> ci: improve precommit and workflows

- README.md
> chore(readme): add licenses badges and remove written line

- src/lib.rs
> fix: rm redundant freesound in frontmatter

- src/lib.rs
Commits](https://www.conventionalcommits.org/en/v1.0.0/) (required)
Minor refactor + one test to make sure filename is actually lowercase.
> chore: improved credit_sound + add test for non lowercase file name

- .pre-commit-config.yaml
- README.md
- src/lib.rs
fix: broken contrib link
chore: pre-commit up
feat: more chars to replace in lib.rs
> chore: minor fixes

- README.md
because README.org is not being picked up, despite all conf adding back README effing md to trick it. will it work?
> fix: trying to fix release-plz

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `freesound-credits`: 0.2.18 -> 0.2.19 (✓ API compatible changes)
<blockquote>
- Manually updating cargo-dist ([#72](https://github.com/andreacfromtheapp/freesound-credits/pull/72)) - ([c2e1063](https://github.com/andreacfromtheapp/freesound-credits/commit/c2e1063a65267d0dd001b4dab319239853e546be))
- Trying to fix release-plz ([#70](https://github.com/andreacfromtheapp/freesound-credits/issues/70)) - ([e2662d3](https://github.com/andreacfromtheapp/freesound-credits/commit/e2662d3d60e9a4c2d4dc4edbef05e280758b11fa))
- Restore readme md cause release-plz ([#67](https://github.com/andreacfromtheapp/freesound-credits/issues/67)) - ([6df070d](https://github.com/andreacfromtheapp/freesound-credits/commit/6df070d1d62817359929b50d1b9ac8607430d …
> chore: release v0.2.19

- .github/workflows/cleanowners.yml
action failed cause missing token. will this work?
> chore: add cleanowners token
